CRITICAL - 2024-04-06 15:16:37 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 29)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->index()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 15:17:19 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 29)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->index()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 15:17:51 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 29)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->index()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 15:18:25 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 29)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->index()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 15:20:15 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->index()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2024-04-06 15:24:45 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(99): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:24:45 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(99): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-04-06 15:26:17 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:17 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:18 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:19 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:19 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:19 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:20 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:20 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:20 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:20 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:20 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:20 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:21 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:21 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:21 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:21 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:21 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:21 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:22 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:22 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:22 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:22 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:22 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:22 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:23 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:23 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:23 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:23 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:23 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:23 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:24 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:24 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:25 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(42): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:26:25 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:26:39 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:26:39 --> pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:26:39 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2024-04-06 15:26:54 --> Undefined array key "id_producto"
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\productoController.php(526): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 526)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\productoController->agregar_productos_x_categoria()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2024-04-06 15:27:28 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(99): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 15:27:28 --> pg_query(): Query failed: ERROR:  no existe la columna «sub_categoria»
LINE 1: SELECT &quot;sub_categoria&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT "sub_cat...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "sub_cat...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "sub_cat...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "sub_cat...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(99): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-04-06 15:33:36 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias('1')
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-06 15:33:36 --> pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias('1')
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-06 15:33:36 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:33:40 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias('1')
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-06 15:33:40 --> pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias('1')
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-06 15:33:40 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:36:06 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias(1)
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-06 15:36:06 --> pg_query(): Query failed: ERROR:  no existe la relación «producto_catego_sub»
LINE 3:         FROM producto_catego_sub
                     ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, '\r\n        SELEC...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('\r\n        SELEC...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('\r\n        SELEC...')
#4 C:\xampp\htdocs\moliendo_cafe\app\Models\productoCategoriaModel.php(19): CodeIgniter\Database\BaseConnection->query('\r\n        SELEC...')
#5 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\Mesas.php(77): App\Models\productoCategoriaModel->id_categorias(1)
#6 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\Mesas->productos_categoria()
#7 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\Mesas))
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2024-04-06 15:37:38 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124795, '1427', Array, '2024-04-06 15:3...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:37:38 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124795, '1427', Array, '2024-04-06 15:3...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:37:38 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:37:40 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124796, '1427', Array, '2024-04-06 15:3...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:37:40 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124796, '1427', Array, '2024-04-06 15:3...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:37:40 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:41:19 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124797, '1427', Array, '2024-04-06 15:4...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:41:19 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124797, '1427', Array, '2024-04-06 15:4...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:41:19 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:42:00 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124798, '1427', Array, '2024-04-06 15:4...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:42:00 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124798, '1427', Array, '2024-04-06 15:4...', '1', '6', '96', '1')
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:42:00 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2024-04-06 15:43:55 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 26)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2024-04-06 15:44:35 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124799, '1427', Array, '2024-04-06 15:4...', 1, 6, '96', 1)
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:44:35 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_ico» en la relación «kardex»
LINE 1: ...&quot;id_factura&quot;, &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124799, '1427', Array, '2024-04-06 15:4...', 1, 6, '96', 1)
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2024-04-06 15:45:07 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «valor_iva» en la relación «kardex»
LINE 1: ... &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico&quot;, &quot;valor_iva...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124800, '1427', Array, '2024-04-06 15:4...', 1, 6, '96', 1)
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:45:07 --> pg_query(): Query failed: ERROR:  no existe la columna «valor_iva» en la relación «kardex»
LINE 1: ... &quot;costo&quot;, &quot;ico&quot;, &quot;iva&quot;, &quot;id_estado&quot;, &quot;valor_ico&quot;, &quot;valor_iva...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'INSERT INTO "ka...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "ka...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "ka...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "ka...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Models\cerrarVentaModel.php(173): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\app\Controllers\pedidos\CerrarVenta.php(175): App\Models\cerrarVentaModel->producto_pedido(Array, 124800, '1427', Array, '2024-04-06 15:4...', 1, 6, '96', 1)
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\pedidos\CerrarVenta->cerrar_venta()
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\pedidos\CerrarVenta))
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2024-04-06 15:47:25 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\factura_pos\facturacionConImpuestosController.php(813): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 813)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\factura_pos\facturacionConImpuestosController->modulo_facturacion()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_pos\facturacionConImpuestosController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2024-04-06 15:48:04 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:48:04 --> pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:48:04 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:51:10 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:51:10 --> pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:51:10 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 15:52:41 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 15:52:41 --> pg_query(): Query failed: ERROR:  no existe la columna «id_apertura»
LINE 3: WHERE &quot;id_apertura&quot; = '96'
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'SELECT "numero"...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "numero"...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "numero"...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "numero"...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\moliendo_cafe\app\Views\caja\historial_aperturas.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\moliendo_cafe\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\moliendo_cafe\system\Common.php(1089): CodeIgniter\View\View->render('caja/historial_...', Array, true)
#11 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\Documento.php(1210): view('caja/historial_...', Array)
#12 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\Documento->aperturas()
#13 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\Documento))
#14 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-04-06 16:09:36 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1918): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1918)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:09:37 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1918): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1918)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:09:39 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1918): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1918)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:12:13 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1907): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1907)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:14:34 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1907): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1907)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:18:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1918): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1918)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:22:14 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1918): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1918)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:24:43 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\consultas_y_reportes\cajaDiariaController.php(1907): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1907)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\consultas_y_reportes\cajaDiariaController->informe_fiscal_desde_caja()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\consultas_y_reportes\cajaDiariaController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:26:34 --> Undefined array key "id_producto"
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\productoController.php(526): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 526)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\productoController->agregar_productos_x_categoria()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2024-04-06 16:26:38 --> Undefined array key "id_producto"
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\productoController.php(526): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 526)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\productoController->agregar_productos_x_categoria()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\productoController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2024-04-06 16:26:41 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «sub_categoria»
LINE 2: FROM &quot;sub_categoria&quot;
             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(145): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(126): CodeIgniter\BaseModel->find()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->crear_sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-04-06 16:26:41 --> pg_query(): Query failed: ERROR:  no existe la relación «sub_categoria»
LINE 2: FROM &quot;sub_categoria&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #157, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(145): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#7 C:\xampp\htdocs\moliendo_cafe\app\Controllers\configuracion\Configuracion.php(126): CodeIgniter\BaseModel->find()
#8 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\configuracion\Configuracion->crear_sub_categoria()
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\configuracion\Configuracion))
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2024-04-06 16:28:01 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_subcategoria» en la relación «producto»
LINE 1: ..._impuesto_saludable&quot;, &quot;valor_impuesto_saludable&quot;, &quot;id_subcat...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'INSERT INTO "pr...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pr...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pr...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pr...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\operacionesProductoController.php(292): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\operacionesProductoController->creacion_producto()
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\operacionesProductoController))
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2024-04-06 16:28:01 --> pg_query(): Query failed: ERROR:  no existe la columna «id_subcategoria» en la relación «producto»
LINE 1: ..._impuesto_saludable&quot;, &quot;valor_impuesto_saludable&quot;, &quot;id_subcat...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'INSERT INTO "pr...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pr...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pr...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pr...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\operacionesProductoController.php(292): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\operacionesProductoController->creacion_producto()
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\operacionesProductoController))
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2024-04-06 16:28:01 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-04-06 16:28:02 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «id_subcategoria» en la relación «producto»
LINE 1: ..._impuesto_saludable&quot;, &quot;valor_impuesto_saludable&quot;, &quot;id_subcat...
                                                             ^ in C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'INSERT INTO "pr...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pr...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pr...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pr...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\operacionesProductoController.php(292): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\operacionesProductoController->creacion_producto()
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\operacionesProductoController))
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2024-04-06 16:28:02 --> pg_query(): Query failed: ERROR:  no existe la columna «id_subcategoria» en la relación «producto»
LINE 1: ..._impuesto_saludable&quot;, &quot;valor_impuesto_saludable&quot;, &quot;id_subcat...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\moliendo_cafe\system\Database\Postgre\Connection.php(135): pg_query(Resource id #156, 'INSERT INTO "pr...')
#2 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pr...')
#3 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pr...')
#4 C:\xampp\htdocs\moliendo_cafe\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pr...', Array, false)
#5 C:\xampp\htdocs\moliendo_cafe\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\moliendo_cafe\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\moliendo_cafe\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\moliendo_cafe\app\Controllers\producto\operacionesProductoController.php(292): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\producto\operacionesProductoController->creacion_producto()
#10 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\producto\operacionesProductoController))
#11 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2024-04-06 16:28:02 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\moliendo_cafe\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\moliendo_cafe\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\moliendo_cafe\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2024-04-06 16:32:25 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\moliendo_cafe\app\Controllers\factura_pos\facturacionConImpuestosController.php(813): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 813)
#1 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(832): App\Controllers\factura_pos\facturacionConImpuestosController->modulo_facturacion()
#2 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_pos\facturacionConImpuestosController))
#3 C:\xampp\htdocs\moliendo_cafe\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\moliendo_cafe\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
